algoritmo "calculo imc"
// Função :
// Autor :
// Data : 19/05/2023
// Seção de Declarações 
var
   M,A, imc: Real
inicio
// Seção de Comandos 
   Escreva ("Massa (kg): ")
   Leia (M)
   Escreva ("Altura (m):")
   Leia (A)
   imc <- m /(a^2)
   Se (IMC>= 18.5) e (IMC<25)  entao
      Escreval("Parabens! Voce esta no seu peso ideal. ")
   Senao
      Escreval("Voce nao esta no seu peso ideal.")
   FimSe
fimalgoritmo
