algoritmo "SOMADOR NUMÉRICO"
// Função :
// Autor :
// Data : 26/08/2023
// Seção de Declarações 
var
      contador, N: inteiro
      soma: inteiro
inicio
// Seção de Comandos 
 contador <- 1
 soma <- 0
 Enquanto contador <=5 faca
      Escreva("Digite um nº: ")
      Leia (N)
      contador <- contador + 1
      soma <- soma + N
 FimEnquanto
 
 Escreva ("A soma dos números é igual a ", soma)
fimalgoritmo
